name: piper_lerobot_image

image_shape: [3, 128, 128]
dataset_path: dp_policy/data/piper_lerobot_128

shape_meta: &shape_meta
  obs:
    camera_0:
      shape: ${task.image_shape}
      type: rgb
    camera_1:
      shape: ${task.image_shape}
      type: rgb
    robot_state:
      shape: [7]
      type: low_dim
  action:
    shape: [7]

env_runner:
  _target_: dp_policy.noop_image_runner.NoOpImageRunner

dataset:
  _target_: dp_policy.lerobot_replay_image_dataset.LerobotReplayImageDataset
  shape_meta: *shape_meta
  dataset_path: ${task.dataset_path}
  horizon: ${horizon}
  pad_before: ${eval:'${n_obs_steps}-1+${n_latency_steps}'}
  pad_after: ${eval:'${n_action_steps}-1'}
  n_obs_steps: ${dataset_obs_steps}
  n_latency_steps: ${n_latency_steps}
  in_memory: false
  seed: 42
  val_ratio: 0.1
  max_train_episodes: null

